compile:
	arduino-cli compile --fqbn rp2040:rp2040:adafruit_feather_usb_host:freq=120,usbstack=tinyusb .
upload:
	arduino-cli upload --fqbn rp2040:rp2040:adafruit_feather_usb_host:freq=120,usbstack=tinyusb .
